# async/await 如果右边方法执行出错该怎么办？

<!-- 使用try、catch包裹await，在catch中处理错误 -->

* 使用.catch捕获代码（catch后的代码还会继续执行）
* 使用try、catch包裹await，在catch中处理错误（try中一旦出错，出错之后代码不会再被执行）
